let dataLevel = [
    { id: "admin", level: "Administrator" },
    { id: "user", level: "User" },
    { id: "umkm", level: "UMKM" },
    { id: "guest", level: "Guest" }
];
let dataKategori = [
    { id: 1, kategori: "Dekorasi" },
    { id: 2, kategori: "Kuliner" },
    { id: 3, kategori: "Fashion" },
    { id: 4, kategori: "Otomotif" },
    { id: 5, kategori: "Frozen Food" },
    { id: 6, kategori: "Furniture" },
    { id: 7, kategori: "Jasa" },
    { id: 8, kategori: "Kecantikan" },
    { id: 9, kategori: "Kue" },
    { id: 10, kategori: "Kuliner" },
    { id: 11, kategori: "Mainan" },
    { id: 12, kategori: "Makanan" },
    { id: 13, kategori: "Makanan dan Minuman" },
    { id: 14, kategori: "Makanan Ringan" },
    { id: 15, kategori: "Minuman" },
    { id: 16, kategori: "Percetakan" },
    { id: 17, kategori: "Perikanan" },
    { id: 18, kategori: "Pertanian" },
    { id: 19, kategori: "Retail" }
];
let dataPengguna = [
    {
        id: 1,
        nama: "Andri Saiful Girsang",
        akun: "andri",
        level: "Administrator",
        status: true,
        kataSandi: "password"
    },
    {
        id: 2,
        nama: "Haditama Yahya Girsang",
        akun: "hadi",
        level: "User",
        status: true,
        kataSandi: "password"
    }
];
let dataUMKM = [
    {
        id: 1,
        namaUsaha: "Tumpeng 01",
        namaPemilik: "Cici Nanti",
        kategoriId: 13,
        deskripsi: "Usaha nasi tumpeng dan catering harian",
        noKtp: 1271011804960001,
        jenisKelamin: false,
        tanggalLahir: "18-04-1996",
        noTelp: "0812-1111-0001",
        email: "tumpeng01@gmail.com",
        alamat: "Perumahan Green City",
        sosialMedia: "@tumpeng.01",
        status: true,
        tanggalRegistrasi: "18-04-2022"
    },
    {
        id: 2,
        namaUsaha: "Turunan Cabe",
        namaPemilik: "Usleni",
        kategoriId: 13,
        deskripsi: "Penjualan sambal dan bumbu masakan",
        noKtp: 1271016806810002,
        jenisKelamin: false,
        tanggalLahir: "06-08-1981",
        noTelp: "0853-5926-4028",
        email: "leni230620@gmail.com",
        alamat: "Dusun VI Desa Bulan Bulan",
        sosialMedia: "@turunancabe",
        status: true,
        tanggalRegistrasi: "21-05-2022"
    },
    {
        id: 3,
        namaUsaha: "Kopi Senja",
        namaPemilik: "Rian Saputra",
        kategoriId: 2,
        deskripsi: "Coffee shop dan minuman kekinian",
        noKtp: 1271011203900003,
        jenisKelamin: true,
        tanggalLahir: "12-03-1990",
        noTelp: "0813-2222-0003",
        email: "kopisenja@gmail.com",
        alamat: "Jl. Kenanga No. 12",
        sosialMedia: "@kopisenja",
        status: true,
        tanggalRegistrasi: "02-06-2022"
    },
    {
        id: 4,
        namaUsaha: "Batik Nusantara",
        namaPemilik: "Siska Ramadhani",
        kategoriId: 3,
        deskripsi: "Produksi dan penjualan kain batik",
        noKtp: 1271014507910004,
        jenisKelamin: false,
        tanggalLahir: "15-07-1991",
        noTelp: "0812-3333-0004",
        email: "batiknusantara@gmail.com",
        alamat: "Jl. Mawar Indah No. 4",
        sosialMedia: "@batiknusantara",
        status: true,
        tanggalRegistrasi: "11-07-2022"
    },
    {
        id: 5,
        namaUsaha: "Toko Mainan Ceria",
        namaPemilik: "Bambang Wijaya",
        kategoriId: 11,
        deskripsi: "Penjualan mainan anak dan edukasi",
        noKtp: 1271012208850005,
        jenisKelamin: true,
        tanggalLahir: "22-08-1985",
        noTelp: "0813-4444-0005",
        email: "ceria.toys@gmail.com",
        alamat: "Jl. Melati Raya No. 8",
        sosialMedia: "@mainanceria",
        status: false,
        tanggalRegistrasi: "19-07-2022"
    },
    {
        id: 6,
        namaUsaha: "Laundry Bersih",
        namaPemilik: "Novi Lestari",
        kategoriId: 7,
        deskripsi: "Jasa laundry kiloan dan satuan",
        noKtp: 1271011409940006,
        jenisKelamin: false,
        tanggalLahir: "14-09-1994",
        noTelp: "0812-5555-0006",
        email: "laundrybersih@gmail.com",
        alamat: "Jl. Flamboyan No. 10",
        sosialMedia: "@laundrybersih",
        status: true,
        tanggalRegistrasi: "28-07-2022"
    },

    {
        id: 7,
        namaUsaha: "Sembako Jaya",
        namaPemilik: "Hendra Gunawan",
        kategoriId: 19,
        deskripsi: "Toko sembako kebutuhan harian",
        noKtp: 1271011002870007,
        jenisKelamin: true,
        tanggalLahir: "10-02-1987",
        noTelp: "0813-6666-0007",
        email: "sembakojaya@gmail.com",
        alamat: "Jl. Karya Bakti No. 5",
        sosialMedia: "@sembakojaya",
        status: true,
        tanggalRegistrasi: "03-08-2022"
    },
    {
        id: 8,
        namaUsaha: "Keripik Maknyus",
        namaPemilik: "Dewi Anggraini",
        kategoriId: 14,
        deskripsi: "Produksi keripik pisang dan singkong",
        noKtp: 1271010506930008,
        jenisKelamin: false,
        tanggalLahir: "05-06-1993",
        noTelp: "0812-7777-0008",
        email: "keripikmaknyus@gmail.com",
        alamat: "Jl. Anggrek No. 21",
        sosialMedia: "@keripikmaknyus",
        status: false,
        tanggalRegistrasi: "14-08-2022"
    },
    {
        id: 9,
        namaUsaha: "Mebel Sejahtera",
        namaPemilik: "Togar Simanjuntak",
        kategoriId: 6,
        deskripsi: "Produksi kursi dan meja kayu",
        noKtp: 1271011505800009,
        jenisKelamin: true,
        tanggalLahir: "15-05-1980",
        noTelp: "0813-8888-0009",
        email: "mebelsejahtera@gmail.com",
        alamat: "Jl. Pinus Raya No. 17",
        sosialMedia: "@mebelsejahtera",
        status: true,
        tanggalRegistrasi: "01-09-2022"
    },
    {
        id: 10,
        namaUsaha: "Fresh Juice Bar",
        namaPemilik: "Maya Putri",
        kategoriId: 15,
        deskripsi: "Minuman jus buah segar",
        noKtp: 1271012209970010,
        jenisKelamin: false,
        tanggalLahir: "22-09-1997",
        noTelp: "0812-9999-0010",
        email: "freshjuice@gmail.com",
        alamat: "Jl. Sakura No. 3",
        sosialMedia: "@freshjuicebar",
        status: true,
        tanggalRegistrasi: "15-09-2022"
    },
    {
        id: 11,
        namaUsaha: "Bakso Mantap",
        namaPemilik: "Ridwan Hakim",
        kategoriId: 2,
        deskripsi: "Penjualan bakso dan mie ayam",
        noKtp: 1271011207880011,
        jenisKelamin: true,
        tanggalLahir: "12-07-1988",
        noTelp: "0812-1000-0011",
        email: "baksomantap@gmail.com",
        alamat: "Jl. Merpati No. 11",
        sosialMedia: "@baksomantap",
        status: true,
        tanggalRegistrasi: "02-10-2022"
    },
    {
        id: 12,
        namaUsaha: "Roti Bunda",
        namaPemilik: "Yuni Kartika",
        kategoriId: 12,
        deskripsi: "Produksi roti dan kue rumahan",
        noKtp: 1271012409900012,
        jenisKelamin: false,
        tanggalLahir: "24-09-1990",
        noTelp: "0812-1000-0012",
        email: "rotibunda@gmail.com",
        alamat: "Jl. Rajawali No. 9",
        sosialMedia: "@rotibunda",
        status: true,
        tanggalRegistrasi: "08-10-2022"
    },
    {
        id: 13,
        namaUsaha: "Cuci Motor Kilat",
        namaPemilik: "Agus Salim",
        kategoriId: 7,
        deskripsi: "Jasa cuci motor dan mobil",
        noKtp: 1271011105850013,
        jenisKelamin: true,
        tanggalLahir: "11-05-1985",
        noTelp: "0812-1000-0013",
        email: "cucikilat@gmail.com",
        alamat: "Jl. Garuda No. 20",
        sosialMedia: "@cucikilat",
        status: false,
        tanggalRegistrasi: "11-10-2022"
    },
    {
        id: 14,
        namaUsaha: "Hijab Cantik",
        namaPemilik: "Nur Aisyah",
        kategoriId: 3,
        deskripsi: "Penjualan hijab dan aksesoris wanita",
        noKtp: 1271010303960014,
        jenisKelamin: false,
        tanggalLahir: "03-03-1996",
        noTelp: "0812-1000-0014",
        email: "hijabcantik@gmail.com",
        alamat: "Jl. Dahlia No. 14",
        sosialMedia: "@hijabcantik",
        status: true,
        tanggalRegistrasi: "15-10-2022"
    },
    {
        id: 15,
        namaUsaha: "Ayam Geprek Mantul",
        namaPemilik: "Doni Saputra",
        kategoriId: 2,
        deskripsi: "Ayam geprek pedas level",
        noKtp: 1271011502920015,
        jenisKelamin: true,
        tanggalLahir: "15-02-1992",
        noTelp: "0812-1000-0015",
        email: "geprekmantul@gmail.com",
        alamat: "Jl. Cendrawasih No. 18",
        sosialMedia: "@ayamgeprekmantul",
        status: true,
        tanggalRegistrasi: "20-10-2022"
    },
    {
        id: 16,
        namaUsaha: "Tani Subur",
        namaPemilik: "M. Yusuf",
        kategoriId: 18,
        deskripsi: "Penjualan pupuk dan bibit tanaman",
        noKtp: 1271011901840016,
        jenisKelamin: true,
        tanggalLahir: "19-01-1984",
        noTelp: "0812-1000-0016",
        email: "tanisubur@gmail.com",
        alamat: "Jl. Melur No. 6",
        sosialMedia: "@tanisubur",
        status: false,
        tanggalRegistrasi: "01-11-2022"
    },
    {
        id: 17,
        namaUsaha: "Salon Ayu",
        namaPemilik: "Putri Amelia",
        kategoriId: 8,
        deskripsi: "Salon kecantikan dan makeup",
        noKtp: 1271012208980017,
        jenisKelamin: false,
        tanggalLahir: "22-08-1998",
        noTelp: "0812-1000-0017",
        email: "salonayu@gmail.com",
        alamat: "Jl. Kemuning No. 2",
        sosialMedia: "@salonayu",
        status: true,
        tanggalRegistrasi: "06-11-2022"
    },
    {
        id: 18,
        namaUsaha: "Berkah Frozen",
        namaPemilik: "Rahmat Hidayat",
        kategoriId: 5,
        deskripsi: "Penjualan makanan beku",
        noKtp: 1271011307910018,
        jenisKelamin: true,
        tanggalLahir: "13-07-1991",
        noTelp: "0812-1000-0018",
        email: "berkahfrozen@gmail.com",
        alamat: "Jl. Mawar Putih No. 13",
        sosialMedia: "@berkahfrozen",
        status: true,
        tanggalRegistrasi: "12-11-2022"
    },
    {
        id: 19,
        namaUsaha: "Kedai Teh Manis",
        namaPemilik: "Fitri Handayani",
        kategoriId: 15,
        deskripsi: "Minuman teh dan boba",
        noKtp: 1271012804950019,
        jenisKelamin: false,
        tanggalLahir: "28-04-1995",
        noTelp: "0812-1000-0019",
        email: "kedaitheh@gmail.com",
        alamat: "Jl. Mangga No. 25",
        sosialMedia: "@kedaithehmanis",
        status: false,
        tanggalRegistrasi: "20-11-2022"
    },
    {
        id: 20,
        namaUsaha: "Digital Print Express",
        namaPemilik: "Eko Prasetyo",
        kategoriId: 16,
        deskripsi: "Jasa printing dan fotocopy",
        noKtp: 1271011706870020,
        jenisKelamin: true,
        tanggalLahir: "17-06-1987",
        noTelp: "0812-1000-0020",
        email: "digitalprint@gmail.com",
        alamat: "Jl. Teratai No. 7",
        sosialMedia: "@digitalprintexpress",
        status: true,
        tanggalRegistrasi: "28-11-2022"
    },
    {
        id: 21,
        namaUsaha: "Kue Lapis Legit",
        namaPemilik: "Murni Sari",
        kategoriId: 9,
        deskripsi: "Produksi kue tradisional",
        noKtp: 1271011006900021,
        jenisKelamin: false,
        tanggalLahir: "10-06-1990",
        noTelp: "0812-1000-0021",
        email: "lapislegit@gmail.com",
        alamat: "Jl. Flamboyan No. 30",
        sosialMedia: "@lapislegit",
        status: true,
        tanggalRegistrasi: "03-12-2022"
    },
    {
        id: 22,
        namaUsaha: "Bengkel Maju",
        namaPemilik: "Joko Susilo",
        kategoriId: 4,
        deskripsi: "Servis motor dan ganti oli",
        noKtp: 1271010504830022,
        jenisKelamin: true,
        tanggalLahir: "05-04-1983",
        noTelp: "0812-1000-0022",
        email: "bengkelmaju@gmail.com",
        alamat: "Jl. Veteran No. 4",
        sosialMedia: "@bengkelmaju",
        status: false,
        tanggalRegistrasi: "09-12-2022"
    },
    {
        id: 23,
        namaUsaha: "Ternak Lele Makmur",
        namaPemilik: "Samsul Bahri",
        kategoriId: 17,
        deskripsi: "Budidaya ikan lele konsumsi",
        noKtp: 1271010802860023,
        jenisKelamin: true,
        tanggalLahir: "08-02-1986",
        noTelp: "0812-1000-0023",
        email: "lelemakmur@gmail.com",
        alamat: "Dusun Mekar Jaya",
        sosialMedia: "@lelemakmur",
        status: true,
        tanggalRegistrasi: "14-12-2022"
    },
    {
        id: 24,
        namaUsaha: "Parfum Refill Wangi",
        namaPemilik: "Lina Marlina",
        kategoriId: 8,
        deskripsi: "Penjualan parfum isi ulang",
        noKtp: 1271012508920024,
        jenisKelamin: false,
        tanggalLahir: "25-08-1992",
        noTelp: "0812-1000-0024",
        email: "parfumwangi@gmail.com",
        alamat: "Jl. Sutomo No. 16",
        sosialMedia: "@parfumwangi",
        status: true,
        tanggalRegistrasi: "20-12-2022"
    },
    {
        id: 25,
        namaUsaha: "Es Campur Segar",
        namaPemilik: "Arifin",
        kategoriId: 15,
        deskripsi: "Es campur dan jus buah",
        noKtp: 1271011109820025,
        jenisKelamin: true,
        tanggalLahir: "11-09-1982",
        noTelp: "0812-1000-0025",
        email: "escampur@gmail.com",
        alamat: "Jl. Diponegoro No. 1",
        sosialMedia: "@escampursegar",
        status: true,
        tanggalRegistrasi: "27-12-2022"
    },
    {
        id: 26,
        namaUsaha: "Aneka Plastik",
        namaPemilik: "Wahyuni",
        kategoriId: 19,
        deskripsi: "Penjualan kebutuhan plastik",
        noKtp: 1271010607940026,
        jenisKelamin: false,
        tanggalLahir: "06-07-1994",
        noTelp: "0812-1000-0026",
        email: "anekaplastik@gmail.com",
        alamat: "Jl. Pembangunan No. 19",
        sosialMedia: "@anekaplastik",
        status: false,
        tanggalRegistrasi: "04-01-2023"
    },
    {
        id: 27,
        namaUsaha: "Tahu Crispy Enak",
        namaPemilik: "Riko Fernando",
        kategoriId: 12,
        deskripsi: "Snack tahu crispy berbagai rasa",
        noKtp: 1271011407990027,
        jenisKelamin: true,
        tanggalLahir: "14-07-1999",
        noTelp: "0812-1000-0027",
        email: "tahucrispy@gmail.com",
        alamat: "Jl. Cemara No. 22",
        sosialMedia: "@tahucrispy",
        status: true,
        tanggalRegistrasi: "11-01-2023"
    },
    {
        id: 28,
        namaUsaha: "Laundry Express",
        namaPemilik: "Sari Dewi",
        kategoriId: 7,
        deskripsi: "Laundry cepat selesai",
        noKtp: 1271012003910028,
        jenisKelamin: false,
        tanggalLahir: "20-03-1991",
        noTelp: "0812-1000-0028",
        email: "laundryexpress@gmail.com",
        alamat: "Jl. Setia Budi No. 12",
        sosialMedia: "@laundryexpress",
        status: true,
        tanggalRegistrasi: "19-01-2023"
    },
    {
        id: 29,
        namaUsaha: "Kebab Sultan",
        namaPemilik: "Fahmi Rizal",
        kategoriId: 2,
        deskripsi: "Kebab dan burger",
        noKtp: 1271010905960029,
        jenisKelamin: true,
        tanggalLahir: "09-05-1996",
        noTelp: "0812-1000-0029",
        email: "kebabsultan@gmail.com",
        alamat: "Jl. Sisingamangaraja No. 27",
        sosialMedia: "@kebabsultan",
        status: false,
        tanggalRegistrasi: "25-01-2023"
    },
    {
        id: 30,
        namaUsaha: "Bunga Florist",
        namaPemilik: "Intan Permata",
        kategoriId: 1,
        deskripsi: "Rangkaian bunga dan buket",
        noKtp: 1271011802980030,
        jenisKelamin: false,
        tanggalLahir: "18-02-1998",
        noTelp: "0812-1000-0030",
        email: "bungaflorist@gmail.com",
        alamat: "Jl. Sakura Indah No. 15",
        sosialMedia: "@bungaflorist",
        status: true,
        tanggalRegistrasi: "30-01-2023"
    }
];
let dataStiker = [
    { id: 1, umkmId: 1, kodeStiker: "Tumpeng 01 01", namaStiker: "Tumpeng 01 Perumahaan Green City Gelembis Bulat 3x3", panjang: 3, lebar: 3, catatan: "Pisah bawah kiri kanan diujung kiri lingkaran", gambar1: "", gambar2: "", status: true },
    { id: 2, umkmId: 1, kodeStiker: "Tumpeng 01 02", namaStiker: "Kotak 5x5", panjang: 5, lebar: 5, catatan: "Laminasi glossy", gambar1: "", gambar2: "", status: true },
    { id: 100, umkmId: 1, kodeStiker: "Tumpeng 01 01", namaStiker: "Bulat 3x3", panjang: 3, lebar: 3, catatan: "Pisah bawah kiri kanan diujung kiri lingkaran", gambar1: "", gambar2: "", status: true },
    { id: 200, umkmId: 1, kodeStiker: "Tumpeng 01 02", namaStiker: "Kotak 5x5", panjang: 5, lebar: 5, catatan: "Laminasi glossy", gambar1: "", gambar2: "", status: true },
    { id: 110, umkmId: 1, kodeStiker: "Tumpeng 01 01", namaStiker: "Bulat 3x3", panjang: 3, lebar: 3, catatan: "Pisah bawah kiri kanan diujung kiri lingkaran", gambar1: "", gambar2: "", status: true },
    { id: 210, umkmId: 1, kodeStiker: "Tumpeng 01 02", namaStiker: "Kotak 5x5", panjang: 5, lebar: 5, catatan: "Laminasi glossy", gambar1: "", gambar2: "", status: true },
    { id: 120, umkmId: 1, kodeStiker: "Tumpeng 01 01", namaStiker: "Bulat 3x3", panjang: 3, lebar: 3, catatan: "Pisah bawah kiri kanan diujung kiri lingkaran", gambar1: "", gambar2: "", status: true },
    { id: 220, umkmId: 1, kodeStiker: "Tumpeng 01 02", namaStiker: "Kotak 5x5", panjang: 5, lebar: 5, catatan: "Laminasi glossy", gambar1: "", gambar2: "", status: true },
    { id: 130, umkmId: 1, kodeStiker: "Tumpeng 01 01", namaStiker: "Bulat 3x3", panjang: 3, lebar: 3, catatan: "Pisah bawah kiri kanan diujung kiri lingkaran", gambar1: "", gambar2: "", status: true },
    { id: 230, umkmId: 1, kodeStiker: "Tumpeng 01 02", namaStiker: "Tumpeng 01 Perumahaan Green City Gelembis Bulat 3x3", panjang: 5, lebar: 5, catatan: "Laminasi glossy", gambar1: "", gambar2: "", status: true },
    { id: 91, umkmId: 1, kodeStiker: "Tumpeng 01 01", namaStiker: "Tumpeng 01 Perumahaan Green City Gelembis Bulat 3x3", panjang: 3, lebar: 3, catatan: "Pisah bawah kiri kanan diujung kiri lingkaran", gambar1: "", gambar2: "", status: true },
    { id: 92, umkmId: 1, kodeStiker: "Tumpeng 01 02", namaStiker: "Kotak 5x5", panjang: 5, lebar: 5, catatan: "Laminasi glossy", gambar1: "", gambar2: "", status: true },
    { id: 9100, umkmId: 1, kodeStiker: "Tumpeng 01 01", namaStiker: "Bulat 3x3", panjang: 3, lebar: 3, catatan: "Pisah bawah kiri kanan diujung kiri lingkaran", gambar1: "", gambar2: "", status: true },
    { id: 9200, umkmId: 1, kodeStiker: "Tumpeng 01 02", namaStiker: "Kotak 5x5", panjang: 5, lebar: 5, catatan: "Laminasi glossy", gambar1: "", gambar2: "", status: true },
    { id: 9110, umkmId: 1, kodeStiker: "Tumpeng 01 01", namaStiker: "Bulat 3x3", panjang: 3, lebar: 3, catatan: "Pisah bawah kiri kanan diujung kiri lingkaran", gambar1: "", gambar2: "", status: true },
    { id: 9210, umkmId: 1, kodeStiker: "Tumpeng 01 02", namaStiker: "Kotak 5x5", panjang: 5, lebar: 5, catatan: "Laminasi glossy", gambar1: "", gambar2: "", status: true },
    { id: 9120, umkmId: 1, kodeStiker: "Tumpeng 01 01", namaStiker: "Bulat 3x3", panjang: 3, lebar: 3, catatan: "Pisah bawah kiri kanan diujung kiri lingkaran", gambar1: "", gambar2: "", status: true },
    { id: 9220, umkmId: 1, kodeStiker: "Tumpeng 01 02", namaStiker: "Kotak 5x5", panjang: 5, lebar: 5, catatan: "Laminasi glossy", gambar1: "", gambar2: "", status: true },
    { id: 9130, umkmId: 1, kodeStiker: "Tumpeng 01 01", namaStiker: "Bulat 3x3", panjang: 3, lebar: 3, catatan: "Pisah bawah kiri kanan diujung kiri lingkaran", gambar1: "", gambar2: "", status: true },
    { id: 9230, umkmId: 1, kodeStiker: "Tumpeng 01 02", namaStiker: "Tumpeng 01 Perumahaan Green City Gelembis Bulat 3x3", panjang: 5, lebar: 5, catatan: "Laminasi glossy", gambar1: "", gambar2: "", status: true },

    { id: 3, umkmId: 2, kodeStiker: "Turunan Cabe 01", namaStiker: "Cemilan 4x4", panjang: 4, lebar: 4, catatan: "Potong rapat", gambar1: "", gambar2: "", status: true },
    { id: 4, umkmId: 2, kodeStiker: "Turunan Cabe 02", namaStiker: "Cabai Bubuk 55 Gram", panjang: 2, lebar: 2, catatan: "Untuk cup kecil", gambar1: "", gambar2: "", status: true },

    { id: 5, umkmId: 3, kodeStiker: "Kopi Senja 01", namaStiker: "Persegi Panjang 8x4", panjang: 8, lebar: 4, catatan: "Background hitam", gambar1: "", gambar2: "", status: true },
    { id: 6, umkmId: 3, kodeStiker: "Kopi Senja 02", namaStiker: "Bulat 5x5", panjang: 5, lebar: 5, catatan: "Logo tengah", gambar1: "", gambar2: "", status: true },

    { id: 7, umkmId: 4, kodeStiker: "Batik Nusantara 01", namaStiker: "Kotak 6x6", panjang: 6, lebar: 6, catatan: "Matte finish", gambar1: "", gambar2: "", status: true },
    { id: 8, umkmId: 4, kodeStiker: "Batik Nusantara 02", namaStiker: "Oval 7x3", panjang: 7, lebar: 3, catatan: "Tulisan emas", gambar1: "", gambar2: "", status: false },

    { id: 9, umkmId: 5, kodeStiker: "Toko Mainan Ceria 01", namaStiker: "Bulat 4x4", panjang: 4, lebar: 4, catatan: "Untuk kemasan mangkok", gambar1: "", gambar2: "", status: true },
    { id: 10, umkmId: 5, kodeStiker: "Toko Mainan Ceria 02", namaStiker: "Kotak 10x5", panjang: 10, lebar: 5, catatan: "Tempel samping", gambar1: "", gambar2: "", status: true },

    { id: 11, umkmId: 6, kodeStiker: "Laundry Bersih 01", namaStiker: "Persegi 4x4", panjang: 4, lebar: 4, catatan: "Cetak merah", gambar1: "", gambar2: "", status: true },
    { id: 12, umkmId: 6, kodeStiker: "Laundry Bersih 02", namaStiker: "Bulat 6x6", panjang: 6, lebar: 6, catatan: "Laminasi doff", gambar1: "", gambar2: "", status: true },

    { id: 13, umkmId: 7, kodeStiker: "Sembako Jaya 01", namaStiker: "Oval 3x5", panjang: 3, lebar: 5, catatan: "Untuk botol", gambar1: "", gambar2: "", status: false },
    { id: 14, umkmId: 7, kodeStiker: "Sembako Jaya 02", namaStiker: "Kotak 5x3", panjang: 5, lebar: 3, catatan: "Background putih", gambar1: "", gambar2: "", status: true },

    { id: 15, umkmId: 8, kodeStiker: "Keripik Maknyus 01", namaStiker: "Bulat 3x3", panjang: 3, lebar: 3, catatan: "Logo besar", gambar1: "", gambar2: "", status: true },
    { id: 16, umkmId: 8, kodeStiker: "Keripik Maknyus 02", namaStiker: "Kotak 7x7", panjang: 7, lebar: 7, catatan: "Cetak full color", gambar1: "", gambar2: "", status: true },

    { id: 17, umkmId: 9, kodeStiker: "Mebel Sejahtera 01", namaStiker: "Oval 6x2", panjang: 6, lebar: 2, catatan: "Tulisan kecil", gambar1: "", gambar2: "", status: true },
    { id: 18, umkmId: 9, kodeStiker: "Mebel Sejahtera 02", namaStiker: "Persegi 5x5", panjang: 5, lebar: 5, catatan: "Tempel tengah", gambar1: "", gambar2: "", status: false },

    { id: 19, umkmId: 10, kodeStiker: "Fresh Juice Bar 01", namaStiker: "Kotak 4x6", panjang: 4, lebar: 6, catatan: "Kemasan burger", gambar1: "", gambar2: "", status: true },
    { id: 20, umkmId: 10, kodeStiker: "Fresh Juice Bar 02", namaStiker: "Bulat 8x8", panjang: 8, lebar: 8, catatan: "Logo hitam putih", gambar1: "", gambar2: "", status: true },

    { id: 21, umkmId: 11, kodeStiker: "Bakso Mantap 01", namaStiker: "Oval 5x2", panjang: 5, lebar: 2, catatan: "Cetak tipis", gambar1: "", gambar2: "", status: true },
    { id: 22, umkmId: 11, kodeStiker: "Bakso Mantap 02", namaStiker: "Kotak 6x4", panjang: 6, lebar: 4, catatan: "Untuk box nasi", gambar1: "", gambar2: "", status: true },

    { id: 23, umkmId: 12, kodeStiker: "Roti Bunda 01", namaStiker: "Bulat 2x2", panjang: 2, lebar: 2, catatan: "Mini size", gambar1: "", gambar2: "", status: false },
    { id: 24, umkmId: 12, kodeStiker: "Roti Bunda 02", namaStiker: "Oval 4x6", panjang: 4, lebar: 6, catatan: "Warna kuning", gambar1: "", gambar2: "", status: true },

    { id: 25, umkmId: 13, kodeStiker: "Cuci Motor Kilat 01", namaStiker: "Kotak 9x4", panjang: 9, lebar: 4, catatan: "Tempel depan", gambar1: "", gambar2: "", status: true },
    { id: 26, umkmId: 13, kodeStiker: "Cuci Motor Kilat 02", namaStiker: "Bulat 5x5", panjang: 5, lebar: 5, catatan: "Logo tengah besar", gambar1: "", gambar2: "", status: true },

    { id: 27, umkmId: 14, kodeStiker: "Hijab Cantik 01", namaStiker: "Oval 3x4", panjang: 3, lebar: 4, catatan: "Tempel roti", gambar1: "", gambar2: "", status: true },
    { id: 28, umkmId: 14, kodeStiker: "Hijab Cantik 02", namaStiker: "Kotak 8x3", panjang: 8, lebar: 3, catatan: "Warna pastel", gambar1: "", gambar2: "", status: false },

    { id: 29, umkmId: 15, kodeStiker: "Ayam Geprek Mantul 01", namaStiker: "Bulat 4x4", panjang: 4, lebar: 4, catatan: "Untuk cup jus", gambar1: "", gambar2: "", status: true },
    { id: 30, umkmId: 15, kodeStiker: "Ayam Geprek Mantul 02", namaStiker: "Persegi 6x6", panjang: 6, lebar: 6, catatan: "Laminasi glossy", gambar1: "", gambar2: "", status: true }
];
let dataOrderan = [
    { id: 1, dataPenggunaId: 1, umkmId: 1, faktur: "RBBB-OLD0001", tanggalOrderan: "21-05-2026", totalStiker: 10 },
    { id: 2, dataPenggunaId: 2, umkmId: 2, faktur: "RBBB-OLD0002", tanggalOrderan: "22-05-2026", totalStiker: 15 },
    { id: 3, dataPenggunaId: 1, umkmId: 3, faktur: "RBBB-OLD0003", tanggalOrderan: "23-05-2026", totalStiker: 20 },
    { id: 4, dataPenggunaId: 2, umkmId: 4, faktur: "RBBB-OLD0004", tanggalOrderan: "24-05-2026", totalStiker: 25 },
    { id: 5, dataPenggunaId: 1, umkmId: 5, faktur: "RBBB-OLD0005", tanggalOrderan: "25-05-2026", totalStiker: 30 },

    { id: 6, dataPenggunaId: 2, umkmId: 6, faktur: "RBBB-OLD0006", tanggalOrderan: "26-05-2026", totalStiker: 12 },
    { id: 7, dataPenggunaId: 1, umkmId: 7, faktur: "RBBB-OLD0007", tanggalOrderan: "27-05-2026", totalStiker: 18 },
    { id: 8, dataPenggunaId: 2, umkmId: 8, faktur: "RBBB-OLD0008", tanggalOrderan: "28-05-2026", totalStiker: 22 },
    { id: 9, dataPenggunaId: 1, umkmId: 9, faktur: "RBBB-OLD0009", tanggalOrderan: "29-05-2026", totalStiker: 14 },
    { id: 10, dataPenggunaId: 2, umkmId: 10, faktur: "RBBB-OLD0010", tanggalOrderan: "30-05-2026", totalStiker: 16 },

    { id: 11, dataPenggunaId: 1, umkmId: 11, faktur: "RBBB-OLD0011", tanggalOrderan: "31-05-2026", totalStiker: 28 },
    { id: 12, dataPenggunaId: 2, umkmId: 12, faktur: "RBBB-OLD0012", tanggalOrderan: "01-06-2026", totalStiker: 35 },
    { id: 13, dataPenggunaId: 1, umkmId: 13, faktur: "RBBB-OLD0013", tanggalOrderan: "02-06-2026", totalStiker: 40 },
    { id: 14, dataPenggunaId: 2, umkmId: 14, faktur: "RBBB-OLD0014", tanggalOrderan: "03-06-2026", totalStiker: 24 },
    { id: 15, dataPenggunaId: 1, umkmId: 15, faktur: "RBBB-OLD0015", tanggalOrderan: "04-06-2026", totalStiker: 19 },

    { id: 16, dataPenggunaId: 2, umkmId: 16, faktur: "RBBB-OLD0016", tanggalOrderan: "05-06-2026", totalStiker: 21 },
    { id: 17, dataPenggunaId: 1, umkmId: 17, faktur: "RBBB-OLD0017", tanggalOrderan: "06-06-2026", totalStiker: 27 },
    { id: 18, dataPenggunaId: 2, umkmId: 18, faktur: "RBBB-OLD0018", tanggalOrderan: "07-06-2026", totalStiker: 32 },
    { id: 19, dataPenggunaId: 1, umkmId: 19, faktur: "RBBB-OLD0019", tanggalOrderan: "08-06-2026", totalStiker: 17 },
    { id: 20, dataPenggunaId: 2, umkmId: 20, faktur: "RBBB-OLD0020", tanggalOrderan: "09-06-2026", totalStiker: 23 },

    { id: 21, dataPenggunaId: 1, umkmId: 21, faktur: "RBBB-OLD0021", tanggalOrderan: "10-06-2026", totalStiker: 29 },
    { id: 22, dataPenggunaId: 2, umkmId: 22, faktur: "RBBB-OLD0022", tanggalOrderan: "11-06-2026", totalStiker: 31 },
    { id: 23, dataPenggunaId: 1, umkmId: 23, faktur: "RBBB-OLD0023", tanggalOrderan: "12-06-2026", totalStiker: 26 },
    { id: 24, dataPenggunaId: 2, umkmId: 24, faktur: "RBBB-OLD0024", tanggalOrderan: "13-06-2026", totalStiker: 20 },
    { id: 25, dataPenggunaId: 1, umkmId: 25, faktur: "RBBB-OLD0025", tanggalOrderan: "14-06-2026", totalStiker: 18 },

    { id: 26, dataPenggunaId: 2, umkmId: 26, faktur: "RBBB-OLD0026", tanggalOrderan: "15-06-2026", totalStiker: 33 },
    { id: 27, dataPenggunaId: 1, umkmId: 27, faktur: "RBBB-OLD0027", tanggalOrderan: "16-06-2026", totalStiker: 37 },
    { id: 28, dataPenggunaId: 2, umkmId: 28, faktur: "RBBB-OLD0028", tanggalOrderan: "17-06-2026", totalStiker: 13 },
    { id: 29, dataPenggunaId: 1, umkmId: 29, faktur: "RBBB-OLD0029", tanggalOrderan: "18-06-2026", totalStiker: 11 },
    { id: 30, dataPenggunaId: 2, umkmId: 30, faktur: "RBBB-OLD0030", tanggalOrderan: "19-06-2026", totalStiker: 42 },

    { id: 31, dataPenggunaId: 1, umkmId: 1, faktur: "RBBB-OLD0031", tanggalOrderan: "20-06-2026", totalStiker: 16 },
    { id: 32, dataPenggunaId: 2, umkmId: 2, faktur: "RBBB-OLD0032", tanggalOrderan: "21-06-2026", totalStiker: 18 },
    { id: 33, dataPenggunaId: 1, umkmId: 3, faktur: "RBBB-OLD0033", tanggalOrderan: "22-06-2026", totalStiker: 20 },
    { id: 34, dataPenggunaId: 2, umkmId: 4, faktur: "RBBB-OLD0034", tanggalOrderan: "23-06-2026", totalStiker: 22 },
    { id: 35, dataPenggunaId: 1, umkmId: 5, faktur: "RBBB-OLD0035", tanggalOrderan: "24-06-2026", totalStiker: 24 },

    { id: 36, dataPenggunaId: 2, umkmId: 6, faktur: "RBBB-OLD0036", tanggalOrderan: "25-06-2026", totalStiker: 26 },
    { id: 37, dataPenggunaId: 1, umkmId: 7, faktur: "RBBB-OLD0037", tanggalOrderan: "26-06-2026", totalStiker: 28 },
    { id: 38, dataPenggunaId: 2, umkmId: 8, faktur: "RBBB-OLD0038", tanggalOrderan: "27-06-2026", totalStiker: 30 },
    { id: 39, dataPenggunaId: 1, umkmId: 9, faktur: "RBBB-OLD0039", tanggalOrderan: "28-06-2026", totalStiker: 32 },
    { id: 40, dataPenggunaId: 2, umkmId: 10, faktur: "RBBB-OLD0040", tanggalOrderan: "29-06-2026", totalStiker: 34 },

    { id: 41, dataPenggunaId: 1, umkmId: 11, faktur: "RBBB-OLD0041", tanggalOrderan: "30-06-2026", totalStiker: 36 },
    { id: 42, dataPenggunaId: 2, umkmId: 12, faktur: "RBBB-OLD0042", tanggalOrderan: "01-07-2026", totalStiker: 38 },
    { id: 43, dataPenggunaId: 1, umkmId: 13, faktur: "RBBB-OLD0043", tanggalOrderan: "02-07-2026", totalStiker: 40 },
    { id: 44, dataPenggunaId: 2, umkmId: 14, faktur: "RBBB-OLD0044", tanggalOrderan: "03-07-2026", totalStiker: 15 },
    { id: 45, dataPenggunaId: 1, umkmId: 15, faktur: "RBBB-OLD0045", tanggalOrderan: "04-07-2026", totalStiker: 17 },

    { id: 46, dataPenggunaId: 2, umkmId: 16, faktur: "RBBB-OLD0046", tanggalOrderan: "05-07-2026", totalStiker: 19 },
    { id: 47, dataPenggunaId: 1, umkmId: 17, faktur: "RBBB-OLD0047", tanggalOrderan: "06-07-2026", totalStiker: 21 },
    { id: 48, dataPenggunaId: 2, umkmId: 18, faktur: "RBBB-OLD0048", tanggalOrderan: "07-07-2026", totalStiker: 23 },
    { id: 49, dataPenggunaId: 1, umkmId: 19, faktur: "RBBB-OLD0049", tanggalOrderan: "08-07-2026", totalStiker: 25 },
    { id: 50, dataPenggunaId: 2, umkmId: 20, faktur: "RBBB-OLD0050", tanggalOrderan: "09-07-2026", totalStiker: 27 }
];

let dataOrderanRinci = [];
let rincianId = 1;
for (let i = 1; i <= 50; i++) {
    for (let j = 1; j <= 5; j++) {
        dataOrderanRinci.push({
            id: rincianId++,
            dataOrderanId: i,
            dataStikerId: ((i + j - 1) % 30) + 1,
            jumlah: (j * 5)
        });
    }
}